### ISSUE TITLE
Build failed on iOS with v2.4.0

### ISSUE THREAD

**Issue by zakster12** [bugsnag/bugsnag-react-native#148]
Thank you for your fast action on the issue https://github.com/bugsnag/bugsnag-react-native/issues/147. I cannot build on iOS because of these issues:

`Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Bugsnag", referenced from:
      objc-class-ref in libBugsnagReactNative.a(BugsnagReactNative.o)
     (maybe you meant: _OBJC_CLASS_$_BugsnagReactNative)
  "_OBJC_CLASS_$_BugsnagConfiguration", referenced from:
      objc-class-ref in libBugsnagReactNative.a(BugsnagReactNative.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

What I did:
1. `npm install bugsnag-react-native@2.4.0 --save`
2. `react-native link bugsnag-react-native`
3. I have initialized Bugsnag in the application:didFinishLoadingWithOptions: `[BugsnagReactNative start];`
4. `#import <BugsnagReactNative/BugsnagReactNative.h>`
5. `import { Client } from 'bugsnag-react-native';
const bugsnag = new Client();`
6. Updated the Info.plist with my key.

![screen shot 2017-10-03 at 12 07 37 pm](https://user-images.githubusercontent.com/25477229/31118060-c4be38c4-a834-11e7-9fef-06ef012bac31.png)
![screen shot 2017-10-03 at 12 08 22 pm](https://user-images.githubusercontent.com/25477229/31118063-c68030b8-a834-11e7-9597-3f4c76f538b6.png)
![screen shot 2017-10-03 at 12 15 09 pm](https://user-images.githubusercontent.com/25477229/31118069-c9fffa16-a834-11e7-8e46-a7106aae13c1.png)
![screen shot 2017-10-03 at 12 15 20 pm](https://user-images.githubusercontent.com/25477229/31118071-cb3f9cce-a834-11e7-894f-b99501a52a32.png)

**Comment by fractalwrench** [comment]
Thanks for the report @zakster12 - I can confirm that it's an issue with how we're linking the native iOS library. A fix will be released shortly.

**Comment by zakster12** [comment]
@fractalwrench Thank you :) I will test it as soon as it's out.

**Comment by aforty** [comment]
Same issue here. Is there a work-around while we wait for the official fix to be pushed?

**Comment by fractalwrench** [comment]
@zakster12 @aforty you should be able to build with the steps given above using v2.4.1, which is available now.

**Comment by gwmccull** [comment]
@fractalwrench thanks for fixing it so quick! I was struggling with the same

**Comment by zakster12** [comment]
Thank you for your fast reaction again but unfortunately I still cannot build the project. Here is the error:

![ghj](https://user-images.githubusercontent.com/25477229/31161948-309b90d8-a8e3-11e7-82d9-ce56f4fbdf89.png)

**Comment by fractalwrench** [comment]
@zakster12 sorry about that, it looks like there are a couple of duplicate symbols within the Sentry/Bugsnag libraries, as both rely on the KSCrash library. Would you be able to open a new issue detailing the versions of Sentry/KSCrash you're using?

This should be fixable by us prefixing any clashing symbols - in the meantime a potential workaround would be to only include one of the two libraries in your application.

**Comment by zakster12** [comment]
@fractalwrench including only the one is not a option right now because we already have our app in production with Sentry but we wanted to see whether BugSnag will give us better understanding/information of the issues we have. But I can open new issue

**Comment by ZeerakHameem32** [comment]
Facing the same issue on v2.23.5. I am using React 0.61.5

**Comment by phillipsam** [comment]
Hi @ZeerakHameem32  - I can see that you have also commented on #433. Can you please confirm exactly what issue you are having when you try to compile for iOS? What error are you seeing?

**Comment by ZeerakHameem32** [comment]
Hi, please look at the following screenshot. I am getting this error while archiving iOS build. It runs fine on the emulator though.
<img width="1186" alt="Screenshot 2020-02-05 at 7 35 40 PM" src="https://user-images.githubusercontent.com/51910597/73851207-eb446b00-484e-11ea-912b-0efdd66d0b7a.png">

I tried v2.23.3 & 2.23.5 both had the same error. I am on React native 0.61.5[](url)
I just upgraded my react native version to 0.61.5. All other dependencies are set but I am unable to run Bugsnag.

**Comment by ZeerakHameem32** [comment]
Update, I wasn't using the full capabilities of React Native 0.61.5. My podfile was not right, i wasn't using "use_native_modules" in the podfile and was adding the path to "bugsnag-react-native" in podfile. That led to that error. 
Once i remove the pod path and added "use_native_modules" React Native auto linking worked and the project compiled / archived.

**Comment by Rutvik17** [comment]
> Hi, please look at the following screenshot. I am getting this error while archiving iOS build. It runs fine on the emulator though.
> <img alt="Screenshot 2020-02-05 at 7 35 40 PM" width="1186" src="https://user-images.githubusercontent.com/51910597/73851207-eb446b00-484e-11ea-912b-0efdd66d0b7a.png">
> 
> I tried v2.23.3 & 2.23.5 both had the same error. I am on React native 0.61.5
> I just upgraded my react native version to 0.61.5. All other dependencies are set but I am unable to run Bugsnag.

under build phase link dependencies to binary
add from pods file and update your headers search path
also update your scheme under product make sure bugsnag is added from pods
