### ISSUE TITLE
auto linking is not working for react native 0.60 version if we use 2.23.1

### ISSUE THREAD

**Issue by naveenthukkani** [bugsnag/bugsnag-react-native#407]
I just update the new version of Bugsnag to 2.23.1and install the pods and I am running app then I am getting below error. can any one help on this.. my react native version is 0.60 

Undefined symbols for architecture x86_64:
  "_RCTGetReactNativeVersion", referenced from:
      ___44-[BugsnagReactNative findReactNativeVersion]_block_invoke in BugsnagReactNative.o
  "_OBJC_CLASS_$_RCTConvert", referenced from:
      objc-class-ref in BugsnagReactNative.o
  "_RCTRegisterModule", referenced from:
      +[BugsnagReactNative load] in BugsnagReactNative.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

I am getting below error also even:
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually: 
  - bugsnag-react-native (to unlink run: "react-native unlink bugsnag-react-native")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above.

**Comment by mattdyoung** [comment]
Hi @naveenthukkani 

Can I check how you're running this?

The correct way would be to either run `react-native run-ios` or launch in Xcode.

If opening in Xcode, please double check that you're opening e.g. `MyProject.xcworkspace` (**not** `MyProject.xcodeproj`) to run the app.

Thanks!

**Comment by naveenthukkani** [comment]
I am sure I am running correctly by using react-native run-ios and if I choose from Xcode also I am running the MyProject.xcworkspace only.. because I am finding pods in my project..

**Comment by mattdyoung** [comment]
@naveenthukkani 
Can you share your `Podfile` and `Podfile.lock`?

Also can I double check you've run `react-native unlink bugsnag-react-native`?

**Comment by naveenthukkani** [comment]
can you please find the Podfile

platform :ios, '9.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'Tele2CustomerApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == 'react-native-config'
        phase = target.project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
        phase.shell_script = "cd ../../"\
        " && RNC_ROOT=./node_modules/react-native-config/"\
        " && export SYMROOT=$RNC_ROOT/ios/ReactNativeConfig"\
        " && ruby $RNC_ROOT/ios/ReactNativeConfig/BuildDotenvConfig.ruby"
        
        target.build_phases << phase
        target.build_phases.move(phase,0)
      end
      if target.name == "React" || target.name == "BugsnagReactNative" || target.name == "RCTRestart"
        target.remove_from_project
      end
    end
   end

  # Pods for Tele2CustomerApp
  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/React'
  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RCTSplashScreen', :path => '../node_modules/rn-splash-screen/rn-splash-screen.podspec'

  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  
  use_native_modules!
  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.15.0'
  
end


podfile.lock


PODS:
  - boost-for-react-native (1.63.0)
  - BoringSSL (10.0.6):
    - BoringSSL/Implementation (= 10.0.6)
    - BoringSSL/Interface (= 10.0.6)
  - BoringSSL/Implementation (10.0.6):
    - BoringSSL/Interface (= 10.0.6)
  - BoringSSL/Interface (10.0.6)
  - BugsnagReactNative (2.23.2):
    - BugsnagReactNative/Core (= 2.23.2)
    - React
  - BugsnagReactNative/Core (2.23.2):
    - React
  - Crashlytics (3.14.0):
    - Fabric (~> 1.10.2)
  - DoubleConversion (1.1.6)
  - Fabric (1.10.2)
  - Firebase/Analytics (5.15.0):
    - Firebase/Core
  - Firebase/Auth (5.15.0):
    - Firebase/CoreOnly
    - FirebaseAuth (= 5.2.0)
  - Firebase/Core (5.15.0):
    - Firebase/CoreOnly
    - FirebaseAnalytics (= 5.4.0)
  - Firebase/CoreOnly (5.15.0):
    - FirebaseCore (= 5.1.10)
  - Firebase/Firestore (5.15.0):
    - Firebase/CoreOnly
    - FirebaseFirestore (= 0.16.1)
  - FirebaseAnalytics (5.4.0):
    - FirebaseCore (~> 5.1)
    - FirebaseInstanceID (~> 3.3)
    - GoogleAppMeasurement (= 5.4.0)
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - FirebaseAuth (5.2.0):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.2)
    - GTMSessionFetcher/Core (~> 1.1)
  - FirebaseAuthInterop (1.0.0)
  - FirebaseCore (5.1.10):
    - GoogleUtilities/Logger (~> 5.2)
  - FirebaseFirestore (0.16.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - FirebaseFirestore/abseil-cpp (= 0.16.1)
    - "gRPC-C++ (= 0.0.5)"
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseFirestore/abseil-cpp (0.16.1):
    - FirebaseAuthInterop (~> 1.0)
    - FirebaseCore (~> 5.1)
    - "gRPC-C++ (= 0.0.5)"
    - leveldb-library (~> 1.20)
    - nanopb (~> 0.3.8)
    - Protobuf (~> 3.1)
  - FirebaseInstanceID (3.3.0):
    - FirebaseCore (~> 5.1)
    - GoogleUtilities/Environment (~> 5.3)
    - GoogleUtilities/UserDefaults (~> 5.3)
  - Folly (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - Folly/Default (= 2018.10.22.00)
    - glog
  - Folly/Default (2018.10.22.00):
    - boost-for-react-native
    - DoubleConversion
    - glog
  - glog (0.3.5)
  - GoogleAppMeasurement (5.4.0):
    - GoogleUtilities/AppDelegateSwizzler (~> 5.2)
    - GoogleUtilities/MethodSwizzler (~> 5.2)
    - GoogleUtilities/Network (~> 5.2)
    - "GoogleUtilities/NSData+zlib (~> 5.2)"
    - nanopb (~> 0.3)
  - GoogleUtilities/AppDelegateSwizzler (5.8.0):
    - GoogleUtilities/Environment
    - GoogleUtilities/Logger
    - GoogleUtilities/Network
  - GoogleUtilities/Environment (5.8.0)
  - GoogleUtilities/Logger (5.8.0):
    - GoogleUtilities/Environment
  - GoogleUtilities/MethodSwizzler (5.8.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/Network (5.8.0):
    - GoogleUtilities/Logger
    - "GoogleUtilities/NSData+zlib"
    - GoogleUtilities/Reachability
  - "GoogleUtilities/NSData+zlib (5.8.0)"
  - GoogleUtilities/Reachability (5.8.0):
    - GoogleUtilities/Logger
  - GoogleUtilities/UserDefaults (5.8.0):
    - GoogleUtilities/Logger
  - "gRPC-C++ (0.0.5)":
    - "gRPC-C++/Implementation (= 0.0.5)"
    - "gRPC-C++/Interface (= 0.0.5)"
  - "gRPC-C++/Implementation (0.0.5)":
    - "gRPC-C++/Interface (= 0.0.5)"
    - gRPC-Core (= 1.14.0)
    - nanopb (~> 0.3)
  - "gRPC-C++/Interface (0.0.5)"
  - gRPC-Core (1.14.0):
    - gRPC-Core/Implementation (= 1.14.0)
    - gRPC-Core/Interface (= 1.14.0)
  - gRPC-Core/Implementation (1.14.0):
    - BoringSSL (~> 10.0)
    - gRPC-Core/Interface (= 1.14.0)
    - nanopb (~> 0.3)
  - gRPC-Core/Interface (1.14.0)
  - GTMSessionFetcher/Core (1.2.2)
  - instabug-reactnative (8.7.0):
    - React
  - leveldb-library (1.22)
  - lottie-ios (3.1.3)
  - lottie-react-native (3.2.1):
    - lottie-ios (~> 3.1.3)
    - React
  - nanopb (0.3.901):
    - nanopb/decode (= 0.3.901)
    - nanopb/encode (= 0.3.901)
  - nanopb/decode (0.3.901)
  - nanopb/encode (0.3.901)
  - Protobuf (3.9.2)
  - RCTRestart (0.0.13):
    - React
  - RCTSplashScreen (5.2.0):
    - React
  - React (0.60.6):
    - React-Core (= 0.60.6)
    - React-DevSupport (= 0.60.6)
    - React-RCTActionSheet (= 0.60.6)
    - React-RCTAnimation (= 0.60.6)
    - React-RCTBlob (= 0.60.6)
    - React-RCTImage (= 0.60.6)
    - React-RCTLinking (= 0.60.6)
    - React-RCTNetwork (= 0.60.6)
    - React-RCTSettings (= 0.60.6)
    - React-RCTText (= 0.60.6)
    - React-RCTVibration (= 0.60.6)
    - React-RCTWebSocket (= 0.60.6)
  - React-Core (0.60.6):
    - Folly (= 2018.10.22.00)
    - React-cxxreact (= 0.60.6)
    - React-jsiexecutor (= 0.60.6)
    - yoga (= 0.60.6.React)
  - React-cxxreact (0.60.6):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-jsinspector (= 0.60.6)
  - React-DevSupport (0.60.6):
    - React-Core (= 0.60.6)
    - React-RCTWebSocket (= 0.60.6)
  - React-jsi (0.60.6):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-jsi/Default (= 0.60.6)
  - React-jsi/Default (0.60.6):
    - boost-for-react-native (= 1.63.0)
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
  - React-jsiexecutor (0.60.6):
    - DoubleConversion
    - Folly (= 2018.10.22.00)
    - glog
    - React-cxxreact (= 0.60.6)
    - React-jsi (= 0.60.6)
  - React-jsinspector (0.60.6)
  - react-native-async-storage (1.2.4):
    - React
  - react-native-config (0.11.7):
    - React
  - react-native-pdf (5.0.12):
    - React
  - react-native-randombytes (3.5.2):
    - React
  - react-native-udp (2.6.0):
    - React
  - react-native-webview (5.7.0):
    - React
  - React-RCTActionSheet (0.60.6):
    - React-Core (= 0.60.6)
  - React-RCTAnimation (0.60.6):
    - React-Core (= 0.60.6)
  - React-RCTBlob (0.60.6):
    - React-Core (= 0.60.6)
    - React-RCTNetwork (= 0.60.6)
    - React-RCTWebSocket (= 0.60.6)
  - React-RCTImage (0.60.6):
    - React-Core (= 0.60.6)
    - React-RCTNetwork (= 0.60.6)
  - React-RCTLinking (0.60.6):
    - React-Core (= 0.60.6)
  - React-RCTNetwork (0.60.6):
    - React-Core (= 0.60.6)
  - React-RCTSettings (0.60.6):
    - React-Core (= 0.60.6)
  - React-RCTText (0.60.6):
    - React-Core (= 0.60.6)
  - React-RCTVibration (0.60.6):
    - React-Core (= 0.60.6)
  - React-RCTWebSocket (0.60.6):
    - React-Core (= 0.60.6)
  - rn-fetch-blob (0.11.2):
    - React-Core
  - RNDeviceInfo (0.21.5):
    - React
  - RNFirebase (5.5.6):
    - Firebase/Core
    - React
    - RNFirebase/Crashlytics (= 5.5.6)
  - RNFirebase/Crashlytics (5.5.6):
    - Crashlytics
    - Fabric
    - Firebase/Core
    - React
  - RNGestureHandler (1.1.0):
    - React
  - RNI18n (2.0.15):
    - React
  - RNKeychain (3.1.1):
    - React
  - RNOpenAppSettings (1.0.0):
    - React
  - RNShare (1.1.3):
    - React
  - RNSVG (9.3.7):
    - React
  - yoga (0.60.6.React)

DEPENDENCIES:
  - BugsnagReactNative (from `../node_modules/bugsnag-react-native`)
  - DoubleConversion (from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`)
  - Firebase/Analytics
  - Firebase/Auth
  - Firebase/Core (~> 5.15.0)
  - Firebase/Firestore
  - Folly (from `../node_modules/react-native/third-party-podspecs/Folly.podspec`)
  - glog (from `../node_modules/react-native/third-party-podspecs/glog.podspec`)
  - instabug-reactnative (from `../node_modules/instabug-reactnative`)
  - lottie-react-native (from `../node_modules/lottie-react-native`)
  - RCTRestart (from `../node_modules/react-native-restart/ios`)
  - RCTSplashScreen (from `../node_modules/rn-splash-screen/rn-splash-screen.podspec`)
  - React (from `../node_modules/react-native/`)
  - React-Core (from `../node_modules/react-native/React`)
  - React-cxxreact (from `../node_modules/react-native/ReactCommon/cxxreact`)
  - React-DevSupport (from `../node_modules/react-native/React`)
  - React-jsi (from `../node_modules/react-native/ReactCommon/jsi`)
  - React-jsiexecutor (from `../node_modules/react-native/ReactCommon/jsiexecutor`)
  - React-jsinspector (from `../node_modules/react-native/ReactCommon/jsinspector`)
  - "react-native-async-storage (from `../node_modules/@react-native-community/async-storage`)"
  - react-native-config (from `../node_modules/react-native-config`)
  - react-native-pdf (from `../node_modules/react-native-pdf`)
  - react-native-randombytes (from `../node_modules/react-native-randombytes`)
  - react-native-udp (from `../node_modules/react-native-udp`)
  - react-native-webview (from `../node_modules/react-native-webview`)
  - React-RCTActionSheet (from `../node_modules/react-native/Libraries/ActionSheetIOS`)
  - React-RCTAnimation (from `../node_modules/react-native/Libraries/NativeAnimation`)
  - React-RCTBlob (from `../node_modules/react-native/Libraries/Blob`)
  - React-RCTImage (from `../node_modules/react-native/Libraries/Image`)
  - React-RCTLinking (from `../node_modules/react-native/Libraries/LinkingIOS`)
  - React-RCTNetwork (from `../node_modules/react-native/Libraries/Network`)
  - React-RCTSettings (from `../node_modules/react-native/Libraries/Settings`)
  - React-RCTText (from `../node_modules/react-native/Libraries/Text`)
  - React-RCTVibration (from `../node_modules/react-native/Libraries/Vibration`)
  - React-RCTWebSocket (from `../node_modules/react-native/Libraries/WebSocket`)
  - rn-fetch-blob (from `../node_modules/rn-fetch-blob`)
  - RNDeviceInfo (from `../node_modules/react-native-device-info`)
  - RNFirebase (from `../node_modules/react-native-firebase/ios`)
  - RNGestureHandler (from `../node_modules/react-native-gesture-handler`)
  - RNI18n (from `../node_modules/react-native-i18n`)
  - RNKeychain (from `../node_modules/react-native-keychain`)
  - RNOpenAppSettings (from `../node_modules/react-native-app-settings`)
  - RNShare (from `../node_modules/react-native-share`)
  - RNSVG (from `../node_modules/react-native-svg`)
  - yoga (from `../node_modules/react-native/ReactCommon/yoga/yoga.podspec`)

SPEC REPOS:
  trunk:
    - boost-for-react-native
    - BoringSSL
    - Crashlytics
    - Fabric
    - Firebase
    - FirebaseAnalytics
    - FirebaseAuth
    - FirebaseAuthInterop
    - FirebaseCore
    - FirebaseFirestore
    - FirebaseInstanceID
    - GoogleAppMeasurement
    - GoogleUtilities
    - "gRPC-C++"
    - gRPC-Core
    - GTMSessionFetcher
    - leveldb-library
    - lottie-ios
    - nanopb
    - Protobuf

EXTERNAL SOURCES:
  BugsnagReactNative:
    :path: "../node_modules/bugsnag-react-native"
  DoubleConversion:
    :podspec: "../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec"
  Folly:
    :podspec: "../node_modules/react-native/third-party-podspecs/Folly.podspec"
  glog:
    :podspec: "../node_modules/react-native/third-party-podspecs/glog.podspec"
  instabug-reactnative:
    :path: "../node_modules/instabug-reactnative"
  lottie-react-native:
    :path: "../node_modules/lottie-react-native"
  RCTRestart:
    :path: "../node_modules/react-native-restart/ios"
  RCTSplashScreen:
    :path: "../node_modules/rn-splash-screen/rn-splash-screen.podspec"
  React:
    :path: "../node_modules/react-native/"
  React-Core:
    :path: "../node_modules/react-native/React"
  React-cxxreact:
    :path: "../node_modules/react-native/ReactCommon/cxxreact"
  React-DevSupport:
    :path: "../node_modules/react-native/React"
  React-jsi:
    :path: "../node_modules/react-native/ReactCommon/jsi"
  React-jsiexecutor:
    :path: "../node_modules/react-native/ReactCommon/jsiexecutor"
  React-jsinspector:
    :path: "../node_modules/react-native/ReactCommon/jsinspector"
  react-native-async-storage:
    :path: "../node_modules/@react-native-community/async-storage"
  react-native-config:
    :path: "../node_modules/react-native-config"
  react-native-pdf:
    :path: "../node_modules/react-native-pdf"
  react-native-randombytes:
    :path: "../node_modules/react-native-randombytes"
  react-native-udp:
    :path: "../node_modules/react-native-udp"
  react-native-webview:
    :path: "../node_modules/react-native-webview"
  React-RCTActionSheet:
    :path: "../node_modules/react-native/Libraries/ActionSheetIOS"
  React-RCTAnimation:
    :path: "../node_modules/react-native/Libraries/NativeAnimation"
  React-RCTBlob:
    :path: "../node_modules/react-native/Libraries/Blob"
  React-RCTImage:
    :path: "../node_modules/react-native/Libraries/Image"
  React-RCTLinking:
    :path: "../node_modules/react-native/Libraries/LinkingIOS"
  React-RCTNetwork:
    :path: "../node_modules/react-native/Libraries/Network"
  React-RCTSettings:
    :path: "../node_modules/react-native/Libraries/Settings"
  React-RCTText:
    :path: "../node_modules/react-native/Libraries/Text"
  React-RCTVibration:
    :path: "../node_modules/react-native/Libraries/Vibration"
  React-RCTWebSocket:
    :path: "../node_modules/react-native/Libraries/WebSocket"
  rn-fetch-blob:
    :path: "../node_modules/rn-fetch-blob"
  RNDeviceInfo:
    :path: "../node_modules/react-native-device-info"
  RNFirebase:
    :path: "../node_modules/react-native-firebase/ios"
  RNGestureHandler:
    :path: "../node_modules/react-native-gesture-handler"
  RNI18n:
    :path: "../node_modules/react-native-i18n"
  RNKeychain:
    :path: "../node_modules/react-native-keychain"
  RNOpenAppSettings:
    :path: "../node_modules/react-native-app-settings"
  RNShare:
    :path: "../node_modules/react-native-share"
  RNSVG:
    :path: "../node_modules/react-native-svg"
  yoga:
    :path: "../node_modules/react-native/ReactCommon/yoga/yoga.podspec"

SPEC CHECKSUMS:
  boost-for-react-native: 39c7adb57c4e60d6c5479dd8623128eb5b3f0f2c
  BoringSSL: e10f92a27043805c01071fe815a5cd98ae8212e7
  BugsnagReactNative: 0a24a1dd2cac88862d67b938f809bec8274130a9
  Crashlytics: 540b7e5f5da5a042647227a5e3ac51d85eed06df
  DoubleConversion: 5805e889d232975c086db112ece9ed034df7a0b2
  Fabric: 706c8b8098fff96c33c0db69cbf81f9c551d0d74
  Firebase: 8bb9268bff82374f2cbaaabb143e725743c316ae
  FirebaseAnalytics: c06f9d70577d79074214700a71fd5d39de5550fb
  FirebaseAuth: 02e969ff430e156d99d4cb842d77b806b71ad7bb
  FirebaseAuthInterop: 0ffa57668be100582bb7643d4fcb7615496c41fc
  FirebaseCore: 35747502d9e8c6ee217385ad04446c7c2aaf9c5c
  FirebaseFirestore: 58043a1c2d2c91efdaa8d8f385cdbaa2ce750cfe
  FirebaseInstanceID: e2fa4cb35ef5558c200f7f0ad8a53e212215f93e
  Folly: 30e7936e1c45c08d884aa59369ed951a8e68cf51
  glog: 1f3da668190260b06b429bb211bfbee5cd790c28
  GoogleAppMeasurement: 98b71f5e04142793729a5ef23e5b96651ff4b70f
  GoogleUtilities: 04fce34bcd5620c1ee76fb79172105c74a4df335
  "gRPC-C++": 19eec1ffd34de29453f5fab5b4697ad0f240ad51
  gRPC-Core: f4836515817c0eb479aeeb9cc27c91c4ba62a9f6
  GTMSessionFetcher: 61bb0f61a4cb560030f1222021178008a5727a23
  instabug-reactnative: 6a4b20152fee125f9b884371ef10ccbf721dff1e
  leveldb-library: 55d93ee664b4007aac644a782d11da33fba316f7
  lottie-ios: 496ac5cea1bbf1a7bd1f1f472f3232eb1b8d744b
  lottie-react-native: b123a79529cc732201091f585c62c89bb4747252
  nanopb: 2901f78ea1b7b4015c860c2fdd1ea2fee1a18d48
  Protobuf: 67fb42ba613def994e61854de2b3164f13790cc4
  RCTRestart: dd19aab87fc1118e05b6b5b91b959105647f56b4
  RCTSplashScreen: 22368020f6297cdc036be8b3b3413de7701b0fd9
  React: 68e7f8dfc27729eade18423072a143120f2f32ab
  React-Core: fc9dace551f6c8c1007dd2d3cb1bc10c90a01d3e
  React-cxxreact: abe59014fce932d41a08bf1aa5dcad9ca8f0a2c5
  React-DevSupport: b0da2fd9ad4ffb25561bf2a328ab84f78f871bdd
  React-jsi: 1a4248256b96fa453536a8dafe11b784e24e789d
  React-jsiexecutor: 2279e559b921d02dfc6253ebef3dcb3a9dc6c07e
  React-jsinspector: a58b86545a0185f69768e78ac96ca9fe43fa3694
  react-native-async-storage: fa98f9a2857afb12128c50c59e506f1925d7bd5b
  react-native-config: 55548054279d92e0e4566ea15a8b9b81028ec342
  react-native-pdf: 3668659dc91de39b73f60da4153568c3d8020f51
  react-native-randombytes: aa2b5e8bf90a9c0402101c62ed7b145f02940e32
  react-native-udp: f218a79de41cbb8b37be0da2af3f5e9efd78a4e8
  react-native-webview: 69ca34f590814ae44260d30e293ab4b7b3eea793
  React-RCTActionSheet: 49f6a67a7efa6688f637296383d453b97ef13645
  React-RCTAnimation: e8047438b2927ebbe630bbf600c7309374075df3
  React-RCTBlob: 2c4b28daca5b3e6e356706d8e0c7436a0e8ef492
  React-RCTImage: 273501f0529775962551613259c20ccdf1a87cd2
  React-RCTLinking: 76c88b3cc98657915a2ba2f20d208e44d0530a43
  React-RCTNetwork: 77c11e672ccdcc33da5d047705f100b016497b15
  React-RCTSettings: f727c25ad26a8a9bd7272a8ba93781bd1f53952a
  React-RCTText: d91537e29e38dc69cf09cbca0875cf5dc7402da6
  React-RCTVibration: 7655d72dfb919dd6d8e135ca108a5a2bd9fcd7b4
  React-RCTWebSocket: 7cd2c8d0f8ddd680dc76404defba7ab1f56b83af
  rn-fetch-blob: f525a73a78df9ed5d35e67ea65e79d53c15255bc
  RNDeviceInfo: e7c5fcde13d40e161d8a27f6c5dc69c638936002
  RNFirebase: ac0de8b24c6f91ae9459575491ed6a77327619c6
  RNGestureHandler: 8a75e1d2f83d73aba148653252953e4bcf363b98
  RNI18n: e2f7e76389fcc6e84f2c8733ea89b92502351fd8
  RNKeychain: 1a121521011702409f5a1009eb8a1effa81000f3
  RNOpenAppSettings: 1169b90a275e9e18c5973e1608949f97d426e7f3
  RNShare: 4f206fa36e384e95a0cbf79f2a92490647e93127
  RNSVG: 2cc66383316fa84d4c672ccfa5e3bac271b6a2af
  yoga: 5079887aa3e4c62142d6bcee493022643ee4d730

PODFILE CHECKSUM: 67f79894eef9e7543a61102f14052ae24c2523ab

COCOAPODS: 1.8.1


I am doing same what you are asking me react-native unlink bugsnag-react-native

**Comment by mattdyoung** [comment]
@naveenthukkani 

I can see this in your `Podfile`:
```
      if target.name == "React" || target.name == "BugsnagReactNative" || target.name == "RCTRestart"
        target.remove_from_project
      end
```

Why are these being removed from the project? That's the likely cause of the errors you're seeing.

**Comment by naveenthukkani** [comment]
no I am causing error before only so that I am removing from my project

**Comment by mattdyoung** [comment]
@naveenthukkani 
It looks like you're using something like the workaround described here:
https://github.com/react-native-community/react-native-svg/issues/621

That relates to conflicts / duplicate symbols where React is included twice. But it appears with your current config the dependencies required for bugsnag-react-native aren't included at all.

Have you recently upgrade to RN 0.60.6. Are you sure the previous workaround is still required? I'd suggest starting by removing these lines:
```
      if target.name == "React" || target.name == "BugsnagReactNative" || target.name == "RCTRestart"
        target.remove_from_project
      end
```
to confirm if you're still seeing the previous error.

If the approach still is required, this blog post may help:
https://sandstorm.de/de/blog/post/react-native-managing-native-dependencies-using-xcode-and-cocoapods.html

But I think this is a generic issue with handling iOS dependencies in RN rather than an issue with Bugsnag.

**Comment by naveenthukkani** [comment]
ok thank you I will look into it...

**Comment by jamieallen59** [comment]
@naveenthukkani did you find a solution?

**Comment by nihp** [comment]
@mattdyoung 

I am getting an error with react-native-bugsnag

`ios/Pods/Headers/Public/BugsnagReactNative/BugsnagReactNative.h:3:9: 'React/RCTBridgeModule.h' file not found`

Can you tell how it producing after upgrading the react-native?

**Comment by nihp** [comment]
I have updated the bugsnag-react-native to 2.23.2 version. Still it failing

**Comment by sanjayradadiya** [comment]
I am facing the same error 

![image](https://user-images.githubusercontent.com/16476120/69776526-a2bf6000-11c2-11ea-81f0-82688a50c6de.png)

**Comment by nihp** [comment]
@mattdyoung  In which version of bugsnag-react-native working with the latest react-native.

I am downgraded to 0.60.0 but still the above error arise for me. 

Any solution. It is existing for me more than 5 days.

**Comment by mattdyoung** [comment]
@nihp @sanjayradadiya 
The issue you've encountered is the one @nihp already raised separately, so I've responded there:
https://github.com/bugsnag/bugsnag-react-native/issues/426#issuecomment-559552663

**Comment by nihp** [comment]
@mattdyoung I have a general question about a huge file generated after upgrade.

After react-native upgrade I found huge files like ios/Index/Datasource/some thing....


What is the use of this files. Shall I need to commit this or need to move in .gitignore.

Can you explain why it get generated?

**Comment by mattdyoung** [comment]
Hi @nihp 

I don't believe that folder is anything to do with Bugsnag or React Native. This post suggests it's used by XCode to speed up subsequent builds and can be excluded from source control:
https://stackoverflow.com/questions/47260788/what-is-the-ios-index-datastore-folder-for-in-react-native-development

**Comment by nihp** [comment]
@mattdyoung Thanks. So only I have mentioned it is a general question

**Comment by nihp** [comment]
How can i exclude that. If I remove this does it make any error in Xcode
