### ISSUE TITLE
Android fails to build with RN 0.59

### ISSUE THREAD

**Issue by kdawgwilk** [bugsnag/bugsnag-react-native#322]
### Description

Trying to upgrade our project to RN 0.59

### Issue

Android fails to compile with the following error:
```
node_modules/bugsnag-react-native/android/src/main/java/com/bugsnag/BugsnagReactNative.java:5: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;

node_modules/bugsnag-react-native/android/src/main/java/com/bugsnag/BugsnagReactNative.java:437: error: cannot find symbol
    public void toStream(@NonNull JsonStream writer) throws IOException {
                          ^
  symbol:   class NonNull
  location: class JavaScriptException
2 errors

FAILURE: Build failed with an exception.
```

### Environment

Library versions:

```shell
    "react-native": "0.59.0",
    "bugsnag-react-native": "^2.15.0",
```

- cocoapods version (if any) (`pod -v`):
- iOS/Android version(s): SDK 28 (this is the new version starting with RN 0.59)
- simulator/emulator or physical device?:
- debug mode or production?:

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [X] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example Repo

- [ ] Create a minimal repository that can reproduce the issue after running
  `yarn install` and `react-native run-ios`/`react-native run-android`
- [ ] Link to it here:

I also followed the guide here https://developer.android.com/jetpack/androidx/migrate

Which turns on Jettifier which should rewrite the imports but it doesn't seem to be working?

**Comment by brunolemos** [comment]
It fails on iOS as well.

```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Bugsnag", referenced from:
      objc-class-ref in libBugsnagReactNative.a(BugsnagReactNative.o)
     (maybe you meant: _OBJC_CLASS_$_BugsnagReactNative)
  "_OBJC_CLASS_$_BugsnagConfiguration", referenced from:
      objc-class-ref in libBugsnagReactNative.a(BugsnagReactNative.o)
  "_bsg_kscrash_setHandlingCrashTypes", referenced from:
      -[BugsnagReactNative startWithOptions:] in libBugsnagReactNative.a(BugsnagReactNative.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by SuperDuperMartin** [comment]
Does anyone know how to solve this?  I guess everyone whos trying to update to rn 0.59 get this error?

**Comment by Cawllec** [comment]
I've addressed some of the potential issues in the comment here: #327.  I don't believe this is a problem with our notifier as we've tested installing the latest release in a React-native 0.59 application with no issues.  However if these issues persist it would be very useful to us to see a reproduction case so that we can ensure that the notifier works correctly in various scenarios.

**Comment by fractalwrench** [comment]
If this behaviour is still a problem, would you be able to create a minimal example that recreates the behaviour, since we've been unable to reproduce?

**Comment by tgensol** [comment]
I got the issue when I added these lines to my gradle.properties :  

```
android.useAndroidX=true
android.enableJetifier=true
```

These lines were added in RN 0.59

**Comment by kdawgwilk** [comment]
It seems this was only an issue once we moved to the new android x dependencies and added the lines that @tgensol mentioned

**Comment by danilobuerger** [comment]
@fractalwrench I think this should be reopened as AndroidX is now enabled by default in 0.60 leading to this error.

https://github.com/facebook/react-native/blob/v0.60.0-rc.0/template/android/gradle.properties

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by fractalwrench** [comment]
Thanks for the help in reproducing this everyone - it appears that `enableJetifier` needs to be `true` to trigger this behaviour. Setting this value to false is a temporary workaround while waiting for the changes in #361 to land.

**Comment by kdawgwilk** [comment]
This is only an issue because this library doesn’t publish built jars to any maven repos.  The jetifier can only convert legacy dependencies to androids if they publish built jars

**Comment by fractalwrench** [comment]
This has been released in v2.20.0.
